swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    post:
        security:
          - Bearer: []
        tags:
          - Transaction Module
        summary: Return all transaction 
        description: API for fetching all transactions of a specific user using their token as proof of authrorisation to fetch them
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
        produces:
          - application/json
        responses:
          '200':
            description: Transactions fetched successully
            schema:
              $ref: '#/definitions/FetchingAllTransactionsResponse'
          '403':
            description: Forbidden 
          '500':
            description: Internal Server Error

  /transaction/{id}:
    get: 
      security:
        - Bearer : []
      tags:
        - Transaction Module
      summary: Returns a transaction by ID
      description: API for fetching a specific transaction using the user token as proof of authorization to fetch it
      parameters:
        - in : header
          type: string
          name: Authorization
          description : Attach Bearer JWT token
          required: true 
        - in : path
          type: string
          name : id
          required: true
          description: Transaction ID.   
      produces:
        - application/json
      responses:
          '200':
            description: Transaction fetched successfully
            schema:
              $ref: '#/definitions/FetchingOneSpecificTransactionResponse'
          '404':
            description: Not found
          '403':
            description: Forbidden 
          '500':
            description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: updating of a specific transaction API
      description: API for updating a specific transaction API
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in : path
          type : string
          name : id
          required: true
          description : id of the specific transaction to update
        - in: body
          name: body
          description: new data on the transaction to update the former one
          required: true
          schema:
            $ref : '#/definitions/TransactionToUpdate'    
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/UpdatingOneSpecificTransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
        #définitions des différents props ------------------
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: delete of a specific transaction API
      description: API for deleting a specific transaction API
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: id
          description: id of the transaction to delete
          required: true   
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successully
          schema:
            $ref: '#/definitions/DeletingOneSpecificTransactionResponse'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header  
definitions:
  TransactionToUpdate:
    type : object
    properties:
      id:
        type: integer
      category:
          type: string
      notes :
        type: string
  FetchingAllTransactionsResponse:
   type: object
   properties:
      status:
        type: integer
      message :
        type : string
      body:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            date:
              type: string
            description:
              type: string
            amount: 
              type : integer
            balance:
              type : integer
            transactionType:
              type: string
            category:
              type : string
            notes : 
              type : string
  FetchingOneSpecificTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount: 
            type : integer
          balance:
            type : integer
          transactionType:
            type: string
          category:
            type : string
          notes : 
            type : string
  UpdatingOneSpecificTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount: 
            type : integer
          balance:
            type : integer
          transactionType:
            type: string
          category:
            type : string
          notes : 
            type : string
  DeletingOneSpecificTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string


